language: generic
os: linux
# dist will be Ubuntu 18.04 LTS Bionic Beaver
dist: bionic
services:
  - docker

before_install:
  - docker build -t jonshallow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jonshallow/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-480904668392"
  bucket_path: "docker-react"
  access_key_id:
    secure: "Encrypted $AWS_ACCESS_KEY="
  secret_access_key:
    secure: "Encrypted $AWS_SECRET_KEY="
  on:
    branch: main